name: "ZAP DAST Scan - Local Docker Juice Shop"

on:
  push:
    branches: [ "secops-zap" ]      # chỉnh theo branch chính của bạn
  pull_request:
    branches: [ "secops-zap" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan local Docker instance of Juice Shop

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Start Juice Shop with Docker
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
          echo "Waiting for Juice Shop to be ready..."
          sleep 40
          docker ps

      # Dùng ZAP fullscan action, target là instance local
      - name: ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000'
          cmd_options: '-a'
          fail_action: false
          allow_issue_writing: false
          # nếu muốn tái dùng rules sẵn có:
          rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a -j'
      # 3. Upload report
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-scan-report
          path: report.html

      - name: Stop Juice Shop container
        if: always()
        run: |
          docker stop juice-shop || true
